homepage:
    pattern: /
    defaults: { _controller: rootiovmailmeBundle:Default:homepage }

plans:
    pattern: /plans
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: registration
        permanent: true

registration:
    pattern: /register
    defaults: { _controller: rootiovmailmeBundle:Default:registration }

registration_alias_1:
    pattern: /registration
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: registration
        permanent: true

registration_alias_2:
    pattern: /subscribe
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: registration
        permanent: true

registration_new:
    pattern: /registration/new
    defaults: { _controller: rootiovmailmeBundle:Default:registrationNew }

donate:
    pattern: /donate
    defaults: { _controller: rootiovmailmeBundle:Default:donate }

terms_of_service:
    pattern: /terms
    defaults: { _controller: rootiovmailmeBundle:Default:termsOfService }

terms_of_service_alias:
    pattern: /termsOfService
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: terms_of_service
        permanent: true

privacy_policy:
    pattern: /privacy
    defaults: { _controller: rootiovmailmeBundle:Default:privacyPolicy }

privacy_policy_alias:
    pattern: /privacyPolicy
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: privacy_policy
        permanent: true

legal_documents:
    pattern: /legal
    defaults: { _controller: rootiovmailmeBundle:Default:legalDocuments }

legal_documents_alias:
    pattern: /legalDocuments
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: legal_documents
        permanent: true

forgot_password:
    pattern: /forgot
    defaults:  { _controller: rootiovmailmeBundle:Default:forgotPassword }

forgot_password_check:
    pattern: /forgot/check
    defaults:  { _controller: rootiovmailmeBundle:Default:forgotPasswordCheck }

reset_password:
    pattern: /reset/{rescueEmail}/{token}/
    defaults:  { _controller: rootiovmailmeBundle:Default:resetPassword }
    requirements:
        token: "[0-9a-f]{64}"

reset_password_check:
    pattern: /reset/{rescueEmail}/{token}/check
    defaults:  { _controller: rootiovmailmeBundle:Default:resetPasswordCheck }
    requirements:
        token: "[0-9a-f]{64}"

login:
    pattern: /login
    defaults:  { _controller: rootiovmailmeBundle:Default:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

user_webmail:
    pattern: /user/webmail/
    defaults:  { _controller: rootiovmailmeBundle:User:webmail }

user_webmail_contacts:
    pattern: /user/webmail/contacts/
    defaults:  { _controller: rootiovmailmeBundle:User:webmailContacts }

user_webmail_settings:
    pattern: /user/webmail/settings/
    defaults:  { _controller: rootiovmailmeBundle:User:webmailSettings }

user_expert:
    pattern: /user/expert
    defaults:  { _controller: rootiovmailmeBundle:User:expert }

user_password:
    pattern: /user/password/
    defaults: { _controller: rootiovmailmeBundle:User:password }

user_password_edit:
    pattern:  /user/password/edit
    defaults: { _controller: rootiovmailmeBundle:User:passwordEdit }

user_forwarding:
    pattern: /user/forwarding/
    defaults: { _controller: rootiovmailmeBundle:User:forwarding }

user_forwarding_edit:
    pattern: /user/forwarding/edit
    defaults: { _controller: rootiovmailmeBundle:User:forwardingEdit }

user_rescue:
    pattern: /user/rescue/
    defaults: { _controller: rootiovmailmeBundle:User:rescue }

user_rescue_edit:
    pattern: /user/rescue/edit
    defaults: { _controller: rootiovmailmeBundle:User:rescueEdit}

user_account:
    pattern: /user/account/
    defaults:  { _controller: rootiovmailmeBundle:User:account }

user_account_suspend:
    pattern: /user/account/suspend
    defaults:  { _controller: rootiovmailmeBundle:User:accountSuspend }
